I'm sorry, but an uncaught exception occurred.

While running game code:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yoshi\\Documents\\RenpyGames\\TBN\\game\\saves\\persistent.1739330740.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\main.py", line 666, in main
    renpy.persistent.update(True)
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\persistent.py", line 434, in update
    save()
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\persistent.py", line 456, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\savelocation.py", line 622, in save_persistent
    l.save_persistent(data)
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\savelocation.py", line 426, in save_persistent
    with open(fn_tmp, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yoshi\\Documents\\RenpyGames\\TBN\\game\\saves\\persistent.1739330740.tmp'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
TBN 1.0
Tue Feb 11 21:23:08 2025
